# Generated by Django 4.1.4 on 2022-12-18 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ('-name',)},
        ),
    ]
