# Generated by Django 4.1.4 on 2022-12-19 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_competition_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='competition',
            field=models.ForeignKey(default=2000, on_delete=django.db.models.deletion.CASCADE, to='matches.competition'),
            preserve_default=False,
        ),
    ]
