# Generated by Django 4.1.4 on 2022-12-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_remove_match_competition_emblem_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ('-utcDateTimeString',)},
        ),
        migrations.RemoveField(
            model_name='match',
            name='utcDate',
        ),
        migrations.RemoveField(
            model_name='match',
            name='utcDateTime',
        ),
        migrations.AddField(
            model_name='match',
            name='utcDateTimeString',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
