# Generated by Django 4.1.4 on 2022-12-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_alter_match_options_remove_match_utcdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='end_date',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start_date',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
