# Generated by Django 4.1.4 on 2022-12-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_alter_competition_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='end_date',
            field=models.DateField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start_date',
            field=models.DateField(max_length=10, null=True),
        ),
    ]
