# Generated by Django 4.1.4 on 2022-12-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_alter_competition_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ('-utcDateTime',)},
        ),
        migrations.RemoveField(
            model_name='match',
            name='awayTeam_score_color',
        ),
        migrations.RemoveField(
            model_name='match',
            name='homeTeam_score_color',
        ),
        migrations.RemoveField(
            model_name='match',
            name='utcDateTimeString',
        ),
        migrations.AddField(
            model_name='match',
            name='utcDateTime',
            field=models.DateTimeField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='awayTeam_crest_url',
            field=models.CharField(default='https://www.svgrepo.com/show/91549/question-mark-inside-a-circle.svg', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='awayTeam_name',
            field=models.CharField(default='TBD', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='awayTeam_shortName',
            field=models.CharField(default='TBD', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='awayTeam_tla',
            field=models.CharField(default='TBD', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='homeTeam_crest_url',
            field=models.CharField(default='https://www.svgrepo.com/show/91549/question-mark-inside-a-circle.svg', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='homeTeam_name',
            field=models.CharField(default='TBD', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_fullTime_awayTeam',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_fullTime_homeTeam',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.CharField(default='TBD', max_length=90, null=True),
        ),
    ]
