# Generated by Django 4.1.4 on 2022-12-21 23:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0010_alter_competition_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='lastly_accessed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
