# Generated by Django 4.1.4 on 2022-12-22 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0011_alter_competition_lastly_accessed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='lastly_accessed',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 22, 14, 50, 57, 829724)),
        ),
    ]
