# Generated by Django 4.1.4 on 2022-12-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.CharField(max_length=50)),
                ('winner', models.CharField(max_length=90)),
                ('stage', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=20)),
                ('awayTeam_name', models.CharField(max_length=40)),
                ('awayTeam_shortName', models.CharField(max_length=40)),
                ('awayTeam_tla', models.CharField(max_length=4)),
                ('awayTeam_crest_url', models.CharField(max_length=200)),
                ('homeTeam_name', models.CharField(max_length=40)),
                ('homeTeam_shortName', models.CharField(max_length=40)),
                ('homeTeam_tla', models.CharField(max_length=4)),
                ('homeTeam_crest_url', models.CharField(max_length=200)),
                ('comptetition_name', models.CharField(max_length=40)),
                ('competition_emblem', models.CharField(max_length=30)),
                ('group', models.CharField(max_length=20)),
                ('match_duration', models.CharField(max_length=30)),
                ('score_fullTime_awayTeam', models.IntegerField(max_length=2)),
                ('score_fullTime_homeTeam', models.IntegerField(max_length=2)),
            ],
        ),
    ]
