# Generated by Django 4.1.4 on 2022-12-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='score_fullTime_awayTeam',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_fullTime_homeTeam',
            field=models.IntegerField(),
        ),
    ]
