# Generated by Django 4.1.4 on 2022-12-14 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ('-utcDate',)},
        ),
        migrations.RemoveField(
            model_name='match',
            name='startDate',
        ),
    ]
