# Generated by Django 4.1.4 on 2022-12-14 18:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_match_options_remove_match_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='utcDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='utcDate',
            field=models.DateField(),
        ),
    ]
