# Generated by Django 4.1.4 on 2022-12-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_match_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='awayTeam_crest_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='awayTeam_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='awayTeam_shortName',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='awayTeam_tla',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='competition_emblem',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='comptetition_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='homeTeam_crest_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='homeTeam_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='homeTeam_shortName',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='homeTeam_tla',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_duration',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='stage',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
