# Generated by Django 4.1.4 on 2022-12-09 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_match_score_fulltime_awayteam_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ('-startDate',)},
        ),
    ]
