# Generated by Django 4.1.4 on 2022-12-09 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_match_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='awayTeam_score_color',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='homeTeam_score_color',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='utcDate',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
